### ISSUE TITLE
I cannot interpret pose classification model structure plz help

### ISSUE THREAD

**Issue by comojin1994** [googlecreativelab/teachablemachine-community#145]
Hello!

I make React Native Home Training application with tfjs-react-native and I want to classify my poses.

I already estimated poses by using tfjs-posenet module.
But, when I input pose coordinates, I got error message
```
Error: Error when checking : expected dense_Dense1_input to have shape [null,14739] but got array with shape [34,1].
```
So I guess many time to interpret what is mean of **14739**, But I cannot get anything.

I read this code(https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/pose/src/teachable-posenet.ts)
```
this.model = tf.sequential({
            layers: [
            // Layer 1.
            tf.layers.dense({
                inputShape: [inputSize],
                units: params.denseUnits,
                activation: 'relu',
                kernelInitializer: varianceScaling, // 'varianceScaling'
                useBias: true
            }),
            // Layer 2 dropout
            tf.layers.dropout({rate: 0.5}),
            // Layer 3. The number of units of the last layer should correspond
            // to the number of classes we want to predict.
            tf.layers.dense({
                units: this.numClasses,
                kernelInitializer: varianceScaling, // 'varianceScaling'
                useBias: false,
                activation: 'softmax'
            })
            ]
        });
        // const optimizer = tf.train.adam(params.learningRate);
        const optimizer = tf.train.rmsprop(params.learningRate);
        this.model.compile({
            optimizer,
            loss: 'categoricalCrossentropy',
            metrics: ['accuracy']
        });
```

and I know that **14739** is **inputSize**.
but I just know that inputSize is related with the number of datas and still cannot interpret what is 14739.

```
// Inputs for posenet
        const inputSize = this.examples[0][1].length;

public async addExample(className: number, sample: Float32Array) {
        // TODO: Do I need to normalize or flip image?
        // const cap = isTensor(sample) ? sample : capture(sample);
        // const example = this.posenet.predict(cap) as tf.Tensor;
        // const embeddingsArray = await this.predictPosenet(sample);

        // save samples of each class separately
        this.examples[className].push(sample);

        // increase our sample counter
        // this.totalSamples++;
    }
```

PLZ HELP ME ;(

**Comment by irealva** [comment]
Hi, 

Thanks so much for writing in. I'm not sure I'm following here — are you trying to replicate our training code but using tfjs-react-native? If so, the pose itself is not the input to the training model, but another activation we're using which is here:

[https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/pose/src/custom-posenet.ts#L231](https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/pose/src/custom-posenet.ts#L231
)

That's why you're getting a size mismatch.

**Comment by irealva** [comment]
Closing this for now. Feel free to reply back if you need any other clarification.

**Comment by AndrewCarluccio** [comment]
@irealva Trying to figure this out as well two years later.  Your link to the poseOutputsToAray function was very helpful. 

However, when trying to set this up in Python:
`combo_data = tf.concat([target_heatmaps,target_offsets],2)
nump = combo_data.numpy()
rav = nump.ravel()
print("Rav Shape")
print(rav.shape)
`
I am finding that the linear shape is 4131 and not the required 14739. What else needs to be done in order to prepare to pass the posenet data to the pose estimation system? Thanks for any insight.

**Comment by irealva** [comment]
@AndrewCarluccio sorry but it's been a while and I'm not actively maintaining this part of the project anymore!

**Comment by AndrewCarluccio** [comment]
No worries @irealva and as I said your previous link was very helpful. I'll keep trying on my side but hopefully another maintainer can chime in.

**Comment by evanjmg** [comment]
Please don't close this issue. The library should make it clear on how to implement posenet with any platform etc
