### ISSUE TITLE
Performance troubles with image classification

### ISSUE THREAD

**Issue by gerchicov-bp** [googlecreativelab/teachablemachine-community#83]
I just opened the website and tried to load some images to classify. The problem is I need to use ~10k images for each class but the browser somehow can upload 6k and for one class only and even in this case my pc becomes too slow.
What could you advice me to do in this case? What about to replace image thumbs with progress bar if it helps?

**Comment by irealva** [comment]
Hi @gerchicov-bp thank you for trying out this tool! Unfortunately because the training happens on device (your data never hits our servers) your actual PC is the one doing the machine learning. Your computer and browser have their own specific limitations for the training speed and data they can handle respectively. That's why we haven't shared upper limits on how much data you can upload - it depends on your computer!
